### ISSUE TITLE
Use official wikipedia client?

### ISSUE THREAD

**Issue by mueller-ma** [jtmcn/archwiki-viewer#45]
I have:
- [x] searched open and closed issues for duplicates
- [x] provided a reproducible result if applicable

----------------------------------------

Is it possible to you the official wikipedia app and change the app name and urls to arch wiki?

**Comment by mueller-ma** [comment]
https://phabricator.wikimedia.org/T107042

**Comment by kevinhinterlong** [comment]
Ok so after taking a look at the ticket, [this blog post](https://blog.go2tech.de/2016/02/how-i-customized-the-wikipedia-app-to-match-the-needs-of-droidwiki-de/) seems like the most helpful resource if I were to switch to their codebase (not sure how much has changed since it was posted). While it would be awesome to get all the features the Wikipedia app I have no idea how long it would take to get it working. 

I'll have to see how difficult this would actually be and then decide.

**Comment by kevinhinterlong** [comment]
I know this is pretty late, but I did end up trying it and there were a couple of problems

1. The ArchWiki doesn't use the most up to date wikimedia, so it would require a significant amount of refactoring to adapt it to the old api
2. ArchWiki is very complicated to browse for different languages because several languages are hosted on the main site, but many are on different websites (possibly using other different versions)

This would really only be feasible if the ArchWiki updated to a newer version and they hosted all of the languages on the same site
