### ISSUE TITLE
Privacy Concern

### ISSUE THREAD

**Issue by stef204** [jtmcn/archwiki-viewer#51]
I have noticed recently that if I browse the ArchWiki on my device using a browser (so not using archwiki-viewer), I get an additional android-like icon in the browser's address bar which, when clicked, opens archwiki-viewer.

I take it this is due to code in archwiki-viewer as opposed to code in the browser?

And it "looks" like browser connections are being tracked by archwiki-viewer or there is some trigger when visiting the the [wiki url](https://wiki.archlinux.org/).with the browser.

This raises a security/privacy concern.

Can you please explain what is going on "behind the scenes" and what is the purpose of this "feature"?  If one is already on the ArchWiki page in the browser, why would one need to open archwiki-viewer then?

It seems the value of archwiki-viewer is to be able to browse the wiki quickly without having the full browser open, etc.

Thanks.

**Comment by kevinhinterlong** [comment]
Yep here's the code in `archwiki-viewer` which is responsible for that.

https://github.com/jtmcn/archwiki-viewer/blob/fe8afb6ca90f503eaf85039b7439dfb26b21475f/app/src/main/AndroidManifest.xml#L24-L34

This is a feature of Android called Intent Filters - there's no tracking going on. Basically it allows other Android apps to figure out if there is another application which can handle this type of URL.

So when your browser sees `"https://wiki.archlinux.org/"` it finds `archwiki-viewer` can open this URL natively and offers to launch the app for you. While this isn't particularly useful from the browser (since it can't tell that the app will basically do the same thing), it could be useful if say someone messaged you a page on the wiki and you clicked it, it should offer to open in the app instead of launching the full browser.

Hopefully that clears things up, but feel free to let me know if you have any other questions.

**Comment by stef204** [comment]
Thanks a lot for your detailed answer, it is quite helpful.  And it beats grepping through the source.
I'll take a look at Intent Filters to learn more.
